name: Azure Static Web Apps CI/CD (recette)

on:
  push:
    branches: [recette]
  pull_request:
    branches: [recette]
    types: [opened, synchronize, reopened, closed]

concurrency: swa-recette-deploy

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy (no build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          # NE PAS passer le token ici -> l'action lira AZURE_STATIC_WEB_APPS_API_TOKEN automatiquement
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          output_location: "/"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
